### ISSUE TITLE
Usage Instruction Set

### ISSUE THREAD

**Issue by ankitatcodingnebula** [ariyanzri/MegaStitch#2]
Hi @ariyanzri . I am keen to try this project on a dataset of mine and would need some guidance on setup and running the scripts to create an orthomosaic. Could you please help?

**Comment by perseus-wy** [comment]
Hi @ariyanzri . I try to stitch the images you provoide with your code , but I do not konw which .py file to start. And in MGRAPH.py, from non_linear_optimizer import Non_Linear_Reprojection_Method, I can not find this package, how do I install this.Could you please help?

**Comment by ariyanzri** [comment]
@ankitatcodingnebula @perseus-wy Thank you both for commenting and creating this issue. I have been trying to find some time to clean the repo and provide clear instructions on how to use the code. I was busy with another project and recently I found some time. In the upcoming week, I will spend some time to do that and once I pushed the changes, I will let you know by leaving another comment here.

**Comment by ariyanzri** [comment]
Hi @ankitatcodingnebula @perseus-wy,

I have updated the repo. I fixed some issues and tested all the methods with different parameters and on different datasets. I also provided a readme file that shows how to run the code. Please let me know if you can run it.

**Comment by perseus-wy** [comment]
Hi @ariyanzri .  I also wonder how do you use it in cmd, could you give some examples?

**Comment by ariyanzri** [comment]
Hi @perseus-wy ,

You are using one of our large datasets. For that one, you would probably need to run it on an HPC system. The whole purpose of this project was to stitch these high resolution large images on super computers. I recommend you to use a smaller dataset on your machine. By the way, if in the future you decided to run the GLEFN dataset on a super computer, you should run it through the Gantry_Geo_correction script. I hope this is useful.

**Comment by perseus-wy** [comment]
Hi @ariyanzri . Could you check the General_GPS_Correction.py, I find in the class Filed, it may can't get the parameter 'settings' from the class Configurations. And this will cause the error.
